# -*- coding: utf-8 -*-
"""Exp 11: Kernel based Image Filtering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ys3zEDfh8BPytul1SGMdLqX71E_yln7K
"""

import numpy as np
import cv2
import matplotlib.pyplot as plt

# Gaussian Kernel Function
def gaussian_kernel(distance, sigma):
    return np.exp(-(distance ** 2) / (2 * sigma ** 2))

# Kernel Based Image Filtering
def kernel_image_filter(image, kernel_size=5, sigma=1.0):
    pad = kernel_size // 2
    padded_img = np.pad(image, pad, mode='reflect')

    filtered_img = np.zeros_like(image, dtype=np.float64)

    # Iterate over each pixel (like predicting each sample in KNN)
    for i in range(image.shape[0]):
        for j in range(image.shape[1]):

            weights_sum = 0.0
            pixel_sum = 0.0

            # Neighborhood (similar to KNN neighbors)
            for x in range(-pad, pad + 1):
                for y in range(-pad, pad + 1):

                    neighbor_pixel = padded_img[i + pad + x, j + pad + y]

                    # Distance in spatial domain
                    dist = np.sqrt(x**2 + y**2)

                    # Kernel weight
                    weight = gaussian_kernel(dist, sigma)

                    pixel_sum += weight * neighbor_pixel
                    weights_sum += weight

            filtered_img[i, j] = pixel_sum / weights_sum

    return filtered_img.astype(np.uint8)

# Load Image
image = cv2.imread("/content/animal.jpg", cv2.IMREAD_GRAYSCALE)

filtered_image = kernel_image_filter(
    image,
    kernel_size=5,
    sigma=1.2
)

# Display Results
plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
plt.title("Original Image")
plt.imshow(image, cmap='gray')
plt.axis("off")

plt.subplot(1,2,2)
plt.title("Kernel Based Filtered Image")
plt.imshow(filtered_image, cmap='gray')
plt.axis("off")

plt.show()
